remote_theme: pmarsceill/just-the-docs
incremental: true

# just-the-docs
title: Bible Study
description: A collection of Bible study materials
base_url: "/bible-study"
url: "https://andrewschmidgit.github.io"
permalink: pretty
aux_links:
    'The Bible (ESV)':
        - 'https://www.esv.org/'
aux_links_new_tab: true

## Search        
search_enabled: true

## Footer
back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://andrewschmidgit.github.io/bible-study" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately